### PR TITLE
Refactoring: responder chain

### PR DESCRIPTION
**Pull request by gavrix**
Refactoring proposal to add responder chain concept. After all this "swifty" discussions, I noticed there are several really weak places in a perfect codebase, and responder chain, lack of it actually, is main of them. The reason why responder chain is necessary — it opens a way to building middleware modules. That is very important in modern frameworks.

These my initial ideas how it could be implemented.

This PR is not yet ready to merge: rather, call for discussion. Let me know what you guys think!

### CODE REVIEW

**Comment by Danappelxx** [comment]
Nice to see this! Middleware is definitely very important. I just wanted to hop in and say that a lot of this functionality could be taken from [open-swift](https://github.com/open-swift/S4) such as middleware, responders, response, body, etc. Great work getting this started!

**Comment by gavrix** [comment]
@Danappelxx yeah, I know that discussion. Some stuff like `Response` and `Request` and `Stream` indeed better be taken from open-swift, there is no so much to differ in possible implementations. The main issue though is that swift package manager is still in early dev state and is only available as part of swift 3 dev snapshots. That means 
1. not compatible with swift2.2
2. unstable within swift3 branch

Some stuff that I proposed like Responder chain implementation, is different than the one in open-swift, and frankly, I don't think Responder chain should be unified at all in open-swift. 

In future when we get stable swift package manager, there is of course only one way to go. With swift2.2  I guess Perfect core maintainers need to pick the best strategy: 
- either use it's own implementation of `Request`, `Response` etc. but API-compatible with open-swift, 
- or integrate part from the code from open-swft using some bootstrapping process.

**Comment by kjessup** [comment]
Thank you for this. My initial comment is that it appears to enforce a synchronous response. This would remove the flexibility to make asynchronous calls from within the handler. The simplest way to fix this would be to, instead of returning a Response from the handler, deliver the response to the .requestCompleted() callback (or something similar).

Have you done any benchmarks to see what sort of overhead this implementation introduces or improves compared to the current impl. in master?

**Comment by gavrix** [comment]
Responder model I offered actually is asynchronous, through `Stream` type body of the response.
Also, I reimplemented Routing (based on Trie) as a `Responder`, and it can detect conflicting routes.

**Comment by dasdcs1** [comment]
http://bit.ly/2dK6Ojk

**Comment by teechap** [comment]
Would this open the door to async middleware? I can't figure out how to make an `HTTPRequestFilter` that works with async calls (e.g. I want my middleware to `.continue` or `.halt` based on a result from Perfect-Redis. I may be totally off-base here--I'd appreciate any help.

**Pull request closed without merging**
