### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Is it fine to add codebeat badge to README? 

codebeat is automated code review tool for Swift, Ruby & Go that helps get instant feedback on code quality. 

"Quick wins" suggested by codebeat could be a nice candidate for a pull request and help other developers become contributors.

FYI. To be fully open and honest. I'm co-founder of codebeat.

### CODE REVIEW

**Comment by kjessup** [comment]
This is great! Let me clean up the issues it points out and I'll approve the request.

**Comment by korzonek** [comment]
Super! Thank you!

BTW... "Quick Wins" are good starting point for people who would like to start contribution to the project. It is a nice guide what to do in order to make a positive impact on overall health of the project.

**Comment by kjessup** [comment]
I (finally) added the badge. Thank you, Codebeat is a very nice system and has helps this code base improve.

**Comment by korzonek** [comment]
@kjessup thank you! We do our best to build tool developers could trust and love. 

If there is anything you would like to see in codebeat, please let us know. Thank you for your help!

**Pull request closed without merging**
